[project]
name = "s3-data-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Allen Njuguna", email = "allennjuguna@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.43.67",
    "polars>=1.43.2",
    "pydantic-settings>=2.15.0",
    "python-dotenv>=1.2.2",
]

[project.scripts]
s3-data-pipeline = "s3_data_pipeline:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.2",
]
